# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: replication.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'replication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11replication.proto\"\x1e\n\x0bTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\"\x1e\n\x0cTaskResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\")\n\x0cWriteRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"\x1f\n\rWriteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1a\n\x0bReadRequest\x12\x0b\n\x03key\x18\x01 \x01(\t\"?\n\x0cReadResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\"-\n\nLoadReport\x12\x11\n\tserver_id\x18\x01 \x01(\t\x12\x0c\n\x04load\x18\x02 \x01(\x05\"\x1e\n\x0cLoadResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\x89\x02\n\x0bReplication\x12)\n\nHandleTask\x12\x0c.TaskRequest\x1a\r.TaskResponse\x12&\n\x05Write\x12\r.WriteRequest\x1a\x0e.WriteResponse\x12#\n\x04Read\x12\x0c.ReadRequest\x1a\r.ReadResponse\x12(\n\nReportLoad\x12\x0b.LoadReport\x1a\r.LoadResponse\x12\'\n\tShareLoad\x12\x0b.LoadReport\x1a\r.LoadResponse\x12/\n\x10RedistributeTask\x12\x0c.TaskRequest\x1a\r.TaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'replication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TASKREQUEST']._serialized_start=21
  _globals['_TASKREQUEST']._serialized_end=51
  _globals['_TASKRESPONSE']._serialized_start=53
  _globals['_TASKRESPONSE']._serialized_end=83
  _globals['_WRITEREQUEST']._serialized_start=85
  _globals['_WRITEREQUEST']._serialized_end=126
  _globals['_WRITERESPONSE']._serialized_start=128
  _globals['_WRITERESPONSE']._serialized_end=159
  _globals['_READREQUEST']._serialized_start=161
  _globals['_READREQUEST']._serialized_end=187
  _globals['_READRESPONSE']._serialized_start=189
  _globals['_READRESPONSE']._serialized_end=252
  _globals['_LOADREPORT']._serialized_start=254
  _globals['_LOADREPORT']._serialized_end=299
  _globals['_LOADRESPONSE']._serialized_start=301
  _globals['_LOADRESPONSE']._serialized_end=331
  _globals['_REPLICATION']._serialized_start=334
  _globals['_REPLICATION']._serialized_end=599
# @@protoc_insertion_point(module_scope)
