# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import replication_pb2 as replication__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in replication_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ReplicationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HandleTask = channel.unary_unary(
                '/Replication/HandleTask',
                request_serializer=replication__pb2.TaskRequest.SerializeToString,
                response_deserializer=replication__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.Write = channel.unary_unary(
                '/Replication/Write',
                request_serializer=replication__pb2.WriteRequest.SerializeToString,
                response_deserializer=replication__pb2.WriteResponse.FromString,
                _registered_method=True)
        self.Read = channel.unary_unary(
                '/Replication/Read',
                request_serializer=replication__pb2.ReadRequest.SerializeToString,
                response_deserializer=replication__pb2.ReadResponse.FromString,
                _registered_method=True)
        self.ReportLoad = channel.unary_unary(
                '/Replication/ReportLoad',
                request_serializer=replication__pb2.LoadReport.SerializeToString,
                response_deserializer=replication__pb2.LoadResponse.FromString,
                _registered_method=True)
        self.ShareLoad = channel.unary_unary(
                '/Replication/ShareLoad',
                request_serializer=replication__pb2.LoadReport.SerializeToString,
                response_deserializer=replication__pb2.LoadResponse.FromString,
                _registered_method=True)
        self.RedistributeTask = channel.unary_unary(
                '/Replication/RedistributeTask',
                request_serializer=replication__pb2.TaskRequest.SerializeToString,
                response_deserializer=replication__pb2.TaskResponse.FromString,
                _registered_method=True)


class ReplicationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HandleTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportLoad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ShareLoad(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RedistributeTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplicationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HandleTask': grpc.unary_unary_rpc_method_handler(
                    servicer.HandleTask,
                    request_deserializer=replication__pb2.TaskRequest.FromString,
                    response_serializer=replication__pb2.TaskResponse.SerializeToString,
            ),
            'Write': grpc.unary_unary_rpc_method_handler(
                    servicer.Write,
                    request_deserializer=replication__pb2.WriteRequest.FromString,
                    response_serializer=replication__pb2.WriteResponse.SerializeToString,
            ),
            'Read': grpc.unary_unary_rpc_method_handler(
                    servicer.Read,
                    request_deserializer=replication__pb2.ReadRequest.FromString,
                    response_serializer=replication__pb2.ReadResponse.SerializeToString,
            ),
            'ReportLoad': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportLoad,
                    request_deserializer=replication__pb2.LoadReport.FromString,
                    response_serializer=replication__pb2.LoadResponse.SerializeToString,
            ),
            'ShareLoad': grpc.unary_unary_rpc_method_handler(
                    servicer.ShareLoad,
                    request_deserializer=replication__pb2.LoadReport.FromString,
                    response_serializer=replication__pb2.LoadResponse.SerializeToString,
            ),
            'RedistributeTask': grpc.unary_unary_rpc_method_handler(
                    servicer.RedistributeTask,
                    request_deserializer=replication__pb2.TaskRequest.FromString,
                    response_serializer=replication__pb2.TaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Replication', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('Replication', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Replication(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HandleTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Replication/HandleTask',
            replication__pb2.TaskRequest.SerializeToString,
            replication__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Replication/Write',
            replication__pb2.WriteRequest.SerializeToString,
            replication__pb2.WriteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Replication/Read',
            replication__pb2.ReadRequest.SerializeToString,
            replication__pb2.ReadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportLoad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Replication/ReportLoad',
            replication__pb2.LoadReport.SerializeToString,
            replication__pb2.LoadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ShareLoad(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Replication/ShareLoad',
            replication__pb2.LoadReport.SerializeToString,
            replication__pb2.LoadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RedistributeTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/Replication/RedistributeTask',
            replication__pb2.TaskRequest.SerializeToString,
            replication__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
